feat:add empty masa.blazor server project
masastack/MASA.Templates pull request #23
Opened 2023-04-14 09:12 UTC by MapleWithoutWords

2023-04-14 14:48 UTC, capdiem requested changes
相比官方的空模板，缺少了太多东西了。在官方的基础上改即可，理论上只会增不会减。

2023-04-14 14:48 UTC, capdiem commented
官方的空模板：https://github.com/dotnet/aspnetcore/blob/v7.0.5/src/ProjectTemplates/Web.ProjectTemplates/content/EmptyBlazorServerWeb-CSharp/.template.config/template.json

2023-04-18 01:56 UTC, MapleWithoutWords commented
> @MapleWithoutWords 你还是没有在空模板的基础上改呀，launchsettings site.css 这些都不完整，ide、cli的json有没有。你直接在空模板上改，这些文件我都不用看。

好哦好哦

2023-04-18 03:02 UTC, capdiem requested changes

2023-04-18 03:02 UTC, capdiem commented on src/Content/BlazorEmptyServer/Pages/Index.razor
官方的空模板Index页好像只有一个Hello world，我们这样如何？

2023-04-18 03:02 UTC, capdiem commented on src/Content/BlazorEmptyServer/Pages/_Host.cshtml
> +    <script src="_content/BlazorComponent/js/blazor-component.js"></script>
JS 移动到 blazor.server.js 下面

2023-04-18 03:02 UTC, capdiem commented on src/Content/BlazorEmptyServer/Pages/_Host.cshtml
> +    <link href="https://cdn.masastack.com/npm/fontawesome/v5.0.13/css/all.css" rel="stylesheet">
这两个注释，默认不启用。

2023-04-18 03:02 UTC, capdiem commented on src/Content/BlazorEmptyServer/Pages/_Host.cshtml
> +    <!-- masa blazor css style -->
相关注释删除。

2023-04-18 03:02 UTC, capdiem commented on src/Content/BlazorEmptyServer/Pages/_Host.cshtml
> +    <link href="_content/Masa.Blazor/css/masa-blazor.min.css" rel="stylesheet" />
移动到 site.css 之前。

2023-04-18 03:02 UTC, capdiem commented on src/Content/BlazorEmptyServer/Pages/_Host.cshtml
> +    <link href="css/site.css" rel="stylesheet" />
少了个scoped的css

2023-04-18 08:09 UTC, MapleWithoutWords commented on src/Content/BlazorEmptyServer/Pages/Index.razor
谷老师说要加个计数器，作为我们Masa.Blazor专属的

2023-04-18 08:13 UTC, capdiem reviewed
还缺少 --cdn

2023-04-18 08:13 UTC, capdiem commented on src/Content/BlazorEmptyServer/Pages/_Host.cshtml
> +    <!--js(should lay the end of file)-->
注释删掉。

2023-04-18 08:20 UTC, capdiem requested changes

2023-04-18 08:20 UTC, capdiem commented on src/Content/BlazorEmptyServer/.template.config/template.json
> +  "defaultName": "EmptyMasaBlazorApp",
```suggestion
  "defaultName": "MasaBlazorApp",
```

2023-04-18 09:44 UTC, capdiem approved these changes
LGTM

2023-04-18 09:44 UTC, merged