completed empty wasm project
masastack/MASA.Templates pull request #25
Opened 2023-04-17 11:24 UTC by MapleWithoutWords

2023-04-17 14:04 UTC, capdiem commented
模板的launchSettings的port是有讲究的，会跟template.json的配置生成的。问题基本和server一样。

2023-04-18 06:06 UTC, MapleWithoutWords commented
> 模板的launchSettings的port是有讲究的，会跟template.json的配置生成的。问题基本和server一样。

已修改

2023-04-18 08:38 UTC, capdiem requested changes

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/dotnetcli.host.json
> +    },
不支持host

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/dotnetcli.host.json
> +    }
这是什么，好像也不用支持。

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/icon.png
没用上，删除。

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/ide.host.json
> +    },
不支持

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/template.json
> +      "condition": "(Hosted && HostIdentifier != \"dotnetcli\" && HostIdentifier != \"dotnetcli-preview\")",
condition 不用

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/template.json
> +  "description": "A empty Masa Blazor WebAssembly template with Masa.Blazor.",
```suggestion
  "description": "A empty WebAssembly template with Masa.Blazor.",
```

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/template.json
> +  "defaultName": "MasaBlazorApp-empty",
```suggestion
  "defaultName": "MasaBlazorApp",
```

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/template.json
> +        },
不需要

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/template.json
> +    },
不需要

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/template.json
> +    },
不需要

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/.template.config/template.json
> +    }
```suggestion
    {
      "condition": "(!skipRestore)",
      "description": "Restore NuGet packages required by this project.",
      "manualInstructions": [
        {
          "text": "Run 'dotnet restore'"
        }
      ],
      "actionId": "210D431B-A78B-4D2F-B762-4ED3E3EA9025",
      "continueOnError": true
    }
```

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/BlazorEmptyWasm.csproj
> +	  <!--#endif-->
缩进不统一

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/wwwroot/manifest.webmanifest
> +  "short_name": "EmptyComponentsWebAssembly-CSharp",
```suggestion
  "name": "BlazorEmptyWasm",
  "short_name": "BlazorEmptyWasm",
```

2023-04-18 08:38 UTC, capdiem commented on src/Content/BlazorEmptyWasm/wwwroot/index.html
> +    <script>navigator.serviceWorker.register('service-worker.js');</script>
```suggestion
    <script>navigator.serviceWorker.register('service-worker.js', { updateViaCache: "none" });</script>
```

2023-04-18 09:16 UTC, capdiem requested changes

2023-04-18 09:16 UTC, capdiem commented on src/Content/BlazorEmptyWasm/Program.cs
> +#endif
只用保留非host的代码

2023-04-18 09:51 UTC, capdiem approved these changes
LGTM

2023-04-18 09:51 UTC, merged